# Generated by Django 2.1.3 on 2018-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181118_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('post', 'order')},
        ),
    ]
