# Generated by Django 2.1.3 on 2018-11-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181118_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post')),
            ],
            options={
                'verbose_name': 'Index page configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('order',)},
        ),
    ]
